name: 🎨 Atualizar Painel 3D do GitHub com BeOnSafe

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  generate-snk:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Clonar o repositório do usuário
        uses: actions/checkout@v3

      - name: 🧬 Gerar animação 3D SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ericvasr
          outputs: |
            ./profile-3d-contrib/github-contribution-grid-snake.svg
            ./profile-3d-contrib/github-contribution-grid-snake.gif

      - name: 💾 Commit e Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib
          git commit -m "🎉 Atualização do painel 3D - Snake animation"
          git push
        continue-on-error: true
