name: Update README Stats

on:
  schedule:
    # Atualiza todo dia às 6:00 UTC (3:00 BRT)
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update-stats:
    name: Update GitHub Statistics
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Refresh GitHub Stats Cache
        run: |
          echo "🔄 Atualizando cache das estatísticas..."

          # Força refresh das estatísticas GitHub
          curl -s "https://github-readme-stats.vercel.app/api?username=ericvasr&show_icons=true&theme=dark&bg_color=0d1117&title_color=ffffff&text_color=c9d1d9&icon_color=58a6ff&border_color=30363d&include_all_commits=true&count_private=true&cache_seconds=0" > /dev/null

          curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=ericvasr&layout=compact&langs_count=8&theme=dark&bg_color=0d1117&title_color=ffffff&text_color=c9d1d9&border_color=30363d&cache_seconds=0" > /dev/null

          curl -s "https://github-readme-streak-stats.herokuapp.com/?user=ericvasr&theme=dark&background=0d1117&border=30363d&stroke=58a6ff&ring=58a6ff&fire=58a6ff&currStreakNum=ffffff&sideNums=ffffff&currStreakLabel=58a6ff&sideLabels=c9d1d9&dates=c9d1d9" > /dev/null

          echo "✅ Cache atualizado com sucesso!"
